[project]
name = "ground"
version = "0.1.0"
description = "system-top python venv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "chime>=0.7.0",
    "colorama>=0.4.6",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "mido>=1.3.3",
    "openai>=1.102.0",
    "pingouin>=0.5.5",
    "psutil>=7.0.0",
    "python-dotenv>=1.1.1",
    "seaborn>=0.13.2",
]
